*** Comments ***

The passwords of the users contain special characters, which may cause issues
when writing them into source files. The passwords below have the backslashes
escaped, so that Robot treats them as literal characters instead of escape 
sequences.

*** Variables ***
${USERNAME1}     alice@example.com
${PASSWORD1}     }3jc\\xJnQ=E=+Q_y/%Hd311bW#6{_Oyj

${USERNAME2}     bob@example.com
${PASSWORD2}     nUL9zA3q=Nt7\\N,0?CL&c74U,Ic)0)dN
