*** Comments ***

The passwords of the users contain special characters, which may cause issues
...    when writing them into source files. The passwords below have the
...    backslashes escaped (\ => \\), so that Robot treats them as literal
...    characters instead of escape sequences.


*** Variables ***
${USER1_USERNAME}     alice@example.com
${USER1_PASSWORD}     }3jc\\xJnQ=E=+Q_y/%Hd311bW#6{_Oyj

${USER2_USERNAME}     bob@example.com
${USER2_PASSWORD}     nUL9zA3q=Nt7\\N,0?CL&c74U,Ic)0)dN
